dist: trusty
sudo: false

node_js:
  - "6"

addons:
  chrome: stable

language: node_js

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g npm@^5

install:
  - npm install -g @angular/cli
  - npm install

script:
  - ng lint --type-check
  - ng test -sr --code-coverage --no-progress
  - npm run codecov
