dist: trusty
sudo: false

language: node_js

node_js:
  - "6"
  - "8"

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g npm@^5

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --single-run --code-coverage --no-progress
  - npm run codecov
